# Generated by Django 3.0.7 on 2020-06-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_eamil_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eamil_active',
            new_name='email_active',
        ),
    ]
